/* SCRIPT PERSONAS SOLICITUD DE TRANSPORTE 
	AUTOR: JOHN LÓPEZ
	FECHA: 26/04/2016
	
*/

SELECT 
	TIPOIDENTSOLICITANTE + IDENTIFICACIONSOLICITANTE AS IDENTIFICACION
	,PRIMERAPELLIDO + SEGUNDOAPELLIDO AS APELLIDOS
	,PRIMERNOMBRE + SEGUNDONOMBRE AS NOMBRES
	,DOMINIONOMBRERUTA
	,J.DESCRIPCION AS JORNADA
	,FECHASELECCIONADA
FROM SOLICITUDTRANSPORTE AS ST WITH (NOLOCK)
JOIN PERSONA AS PER  WITH (NOLOCK)
	ON ST.IDENTIFICACIONSOLICITANTE = PER.NUMEROIDENTIFICACION 
JOIN PERSONARUTA AS PR WITH (NOLOCK)
	ON ST.IDENTIFICACIONSOLICITANTE = PR.NUMEROIDENTIFICACIONPASAJERO
JOIN BUSRUTA AS BR WITH (NOLOCK)
	ON PR.IDBUSRUTA = BR.IDBUSRUTA and FECHACALENDARIO = '19000101' 
JOIN DOMINIO  AS J WITH(NOLOCK) 
	ON J.DOMINIO = 'JornadaTransporte' and J.VALOR = BR. DOMINIOJORNADA
JOIN FECHACAMBIOTRANSPORTE AS FCT WITH (NOLOCK)
	ON ST.IDSOLICITUDTRANSPORTE = FCT.IDSOLICITUDTRANSPORTE
ORDER BY  FECHASELECCIONADA ASC



