USE [SGS]
GO
/****** OBJECT:  STOREDPROCEDURE [DBO].[PR_SGS_RPT_GRAFICASPERFILIMC]    SCRIPT DATE: 9/02/2017 8:49:41 A. M. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/************************************************************************        
NOMBRE DEL PROGRAMA:	[dbo].[PR_SGS_RPT_ClasificacionIMC]         
DESCRIPCIÓN:			DEVUELVE UN LISTADO DE ESTUDIANTES CON NOMBRE Y CURSOS
						SEGÚN LA DESVIACIÓN ESTAND AR DE IMC SELECCIONADA.
PARÁMETROS DE ENTRADA: 	
						 @idP_IMCCOMENTARIO VARCHAR (50)
						,@idP_TOMA INT
						,@idP_ANIOLECTIVO INT	

PARÁMETROS DE SALIDA:   NO APLICA.  
RESULTADO:				MUESTRA EL CONSOLIDADO DE LOS REGISTROS POR ESTUDIANTE SEGUN
						CLASIFICACIÓN DE LAS DEVACIONES INTERNAS DE IMC..		
CÓDIGOS DE ERROR:		NO EXISTEN CÓDIGOS DE EXCEPCIÓN PERSONALIZADOS.  
************************************************************************/
ALTER PROCEDURE  [dbo].[PR_SGS_RPT_ClasificacionIMC] 
		 
		 
		 @idP_PeriodoLectivo INT				 					 
		,@idP_Seccion INT
		,@idP_Nivel VARCHAR (60)
		,@idP_Curso VARCHAR(60)
	    ,@idP_ClasifcacionIMC VARCHAR (50)
		,@idP_Toma INT

AS
BEGIN
DECLARE @Cursos TABLE 
	(
		IdCursoSeleccionado VARCHAR(60)
	)
INSERT INTO @Cursos
SELECT CR.Valor 
FROM F_SGS_Split(@idP_Curso, ',') AS CR


	SELECT 
		 C.NOMBRE AS Curso
		,(ISNULL(P.PRIMERAPELLIDO,'') + ' ' +ISNULL(P.SEGUNDOAPELLIDO,'')+'  ' + ISNULL(P.PRIMERNOMBRE, '') + ' ' + ISNULL(P.SEGUNDONOMBRE, '')) AS NombreEstudiante
		, EPT.PESO AS Peso
		, EPT.TALLA AS Talla
		, EPT.IMC AS IMC
		, D.DESCRIPCION AS Desviacion
		, COM.DESCRIPCION AS Comentario 

	FROM ESTUDIANTEPESOTALLA AS EPT 

		LEFT JOIN PERSONA AS P 
			ON  EPT.TIPOIDENTIFICACION = P.TIPOIDENTIFICACION 
			AND EPT.NUMEROIDENTIFICACION = P.NUMEROIDENTIFICACION

		INNER JOIN ESTUDIANTECURSO AS EC 
			ON  EC.TIPOIDENTIFICACIONESTUDIANTE = EPT.TIPOIDENTIFICACION 
			AND EC.NUMEROIDENTIFICACIONESTUDIANTE = EPT.NUMEROIDENTIFICACION

		INNER JOIN CURSO AS C 
			ON EC.IDCURSO = C.IDCURSO

		LEFT JOIN DOMINIO AS D 
			ON  D.DOMINIO = 'IMCDESVIACION' 
			AND D.VALOR = EPT.TIPOIMC

		LEFT JOIN DOMINIO AS COM 
			ON 	COM.DOMINIO = 'IMCCOMENTARIO' 
			AND COM.VALOR = EPT.TIPOIMC

		LEFT JOIN PERIODOLECTIVO AS PER 
			ON PER.ID = EPT.IDANIOACADEMICO

		LEFT JOIN DOMINIO AS TOM 
			ON TOM.VALOR = EPT.IDTOMA
			AND TOM.DOMINIO = 'TOMAPESOTALLA'

		INNER JOIN @Cursos AS CURS
			ON C.IdCurso = CURS.IdCursoSeleccionado

	WHERE
		EPT.IDANIOACADEMICO=@idP_PeriodoLectivo
		AND  EPT.IDTOMA  = @idP_Toma
		AND  EPT.TIPOIMC = @idP_ClasifcacionIMC

	ORDER BY
		C.IDCURSO, NombreEstudiante

END